# Generated by Django 5.2.8 on 2025-11-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_area', models.IntegerField(max_length=8)),
                ('number', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=4)),
                ('requisites_text', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('requisites_parsed', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'subject_areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'subject_areas',
                'managed': False,
            },
        ),
    ]
